# Generated by Django 4.2.8 on 2023-12-28 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
