# Generated by Django 4.2.8 on 2023-12-30 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_images_img'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Images',
            new_name='Imagez',
        ),
    ]
