# Generated by Django 4.2.8 on 2023-12-30 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_rename_images_imagez'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Imagez',
            new_name='Images',
        ),
    ]
