# Generated by Django 4.2.8 on 2024-01-02 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_rename_imagez_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='images',
            name='name',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
