# Generated by Django 4.2.8 on 2024-01-02 01:41

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_images_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='name',
            field=models.CharField(max_length=10, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='Partitions',
            fields=[
                ('id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='app.images')),
                ('position', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)])),
                ('image_partition', models.ImageField(upload_to='')),
                ('part_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='part_name', to='app.images', to_field='name')),
            ],
        ),
    ]
