# Generated by Django 4.2.8 on 2024-01-02 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_images_name_partitions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='partitions',
            old_name='part_name',
            new_name='partition_name',
        ),
        migrations.AlterField(
            model_name='partitions',
            name='id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='app.images'),
        ),
    ]
