# Generated by Django 4.2.8 on 2024-01-03 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_alter_partition_image_partition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='img',
            field=models.CharField(blank=True, max_length=1000001, null=True),
        ),
        migrations.AlterField(
            model_name='partition',
            name='image_partition',
            field=models.CharField(blank=True, max_length=100000, null=True),
        ),
    ]
