# Generated by Django 4.2.8 on 2024-01-04 01:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partition',
            name='partition_id',
        ),
        migrations.DeleteModel(
            name='Images',
        ),
        migrations.DeleteModel(
            name='Partition',
        ),
    ]
