# Generated by Django 4.2.8 on 2024-01-04 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='img',
            field=models.ImageField(blank=True, max_length=1000001, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='partition',
            name='image_partition',
            field=models.ImageField(blank=True, max_length=100000, null=True, upload_to=''),
        ),
    ]
