# Generated by Django 4.2.8 on 2024-03-08 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partition',
            name='partition_id',
        ),
        migrations.DeleteModel(
            name='Images',
        ),
        migrations.DeleteModel(
            name='Partition',
        ),
    ]
